name: Check for markdown code blocks in issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  check_markdown:
    runs-on: ubuntu-latest
    name: Markdown issue 

    steps:
    - name: Check if markdown code is used
      id: check_markdown
      run: |
        ISSUE_BODY="${{ github.event.issue.body }}"

        # Check if the issue body contains Markdown inline code or code block (`` ` ``)
        if echo "$ISSUE_BODY" | grep -q "\`"; then
          echo "Markdown code detected."
        else
          echo "No Markdown code detected."
          echo "markdown_used=false" >> $GITHUB_ENV
        fi

    - name: Comment on the issue if no Markdown code is detected
      if: env.markdown_used == 'false'
      run: |
        ISSUE_NUMBER="${{ github.event.issue.number }}"
        REPO="${{ github.repository }}"

        # Define COMMENT_BODY with backticks directly
        COMMENT_BODY="Please use markdown syntax (&#96;&#96;) for code snippets in your issue. You have confirmed the checkbox that you are using markdown, but none was recognized here. The markdown syntax makes your issue more readable and makes it easier to find a solution to your problem more quickly.\\n\\nExamples:\nThe symbol &#96; turns &#96;code&#96; into \`code\`.\\n\\nFor more code use &#96; three times at the beginning and at the end like this:\\n&#96;&#96;&#96;\\nsome\\ncode\\n&#96;&#96;&#96;\\nturns into:\\n\`\`\`\\nsome\\ncode\\n\`\`\`\\nPlease edit your outgoing post immediately. If you think that this hint is not necessary and you have correctly used markdown, then you can simply ignore this message."
        # Post a comment on the issue
        curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"body\":\"${COMMENT_BODY}\"}" \
          "https://api.github.com/repos/${REPO}/issues/${ISSUE_NUMBER}/comments"
